import { Poppins } from "next/font/google";
import "../styles/globals.css";

const poppins = Poppins({  
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ["latin"],
  style: ['italic', 'normal'],
  display: 'swap',
});

export const metadata = {
  title: "Boostive App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
